name: chatcalling
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
      
  intl: ^0.17.0  
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.8
  cloud_firestore: ^3.4.0
  mime: ^1.0.2
  hive: ^2.2.3
  internet_connection_checker: ^0.0.1+3
  path_provider: ^2.0.4
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  uuid: ^3.0.6
  flutter_svg: ^1.1.5
  badges: ^2.0.3
  emoji_picker_flutter: ^1.3.1
  just_audio: ^0.9.29
  just_waveform: ^0.0.3
  flutter_sound: ^9.2.13
  build_runner: ^2.1.2
  grouped_list: ^5.1.2
  
dependency_overrides:
  cloud_firestore_web: ^2.8.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  firebase_storage_mocks: ^0.5.1
  fake_cloud_firestore: ^1.2.4
  bloc_test: ^9.1.0

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  fonts:          
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100 
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300 
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600 
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900