// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBQzzyiUE0jGDbOOrwvQq0ZvXvbYUTy7o',
    appId: '1:820559575255:web:bf52538621ffe56b1b5892',
    messagingSenderId: '820559575255',
    projectId: 'chatcalling-63eb0',
    authDomain: 'chatcalling-63eb0.firebaseapp.com',
    databaseURL: 'https://chatcalling-63eb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatcalling-63eb0.appspot.com',
    measurementId: 'G-KKBY57NSMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ6LJkksdnEbuz5QI967822pCoqRADp2M',
    appId: '1:820559575255:android:8bcab3b44c6d691c1b5892',
    messagingSenderId: '820559575255',
    projectId: 'chatcalling-63eb0',
    databaseURL: 'https://chatcalling-63eb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatcalling-63eb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqnXk_Zoa2V4M8GSJfKqrdOidbKO07By8',
    appId: '1:820559575255:ios:3db85d106793a6b81b5892',
    messagingSenderId: '820559575255',
    projectId: 'chatcalling-63eb0',
    databaseURL: 'https://chatcalling-63eb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatcalling-63eb0.appspot.com',
    androidClientId: '820559575255-b0m5kdhal8826dvt37djs6kkqj51hj9k.apps.googleusercontent.com',
    iosClientId: '820559575255-puk04rcamkqh4prt67fll9b3635c3jd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
